/**
 * Kuratierte Emoji-Auswahl für den Messenger.
 *
 * Eingefügt wird der Unicode-Codepoint, nicht ein Bild. Auf Apple-Geräten
 * rendert das System dafür die Apple-Emoji ("Apple Color Emoji") — genau die
 * Darstellung, die Nutzer:innen von iPhone und Mac kennen. Auf anderen
 * Systemen erscheint der jeweilige Systemsatz; Apples Grafiken dürfen nicht
 * mitgeliefert werden, sie sind urheberrechtlich geschützt.
 *
 * Die Schriftreihenfolge in `globals.css` stellt Apple Color Emoji nach vorn.
 */

export type EmojiEntry = { char: string; keywords: string[] };
export type EmojiCategory = { id: string; label: string; icon: string; emojis: EmojiEntry[] };

const e = (char: string, ...keywords: string[]): EmojiEntry => ({ char, keywords });

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😊",
    emojis: [
      e("😀", "grinsen", "lachen", "freude"),
      e("😃", "grinsen", "fröhlich"),
      e("😄", "lachen", "glücklich"),
      e("😁", "strahlen", "grinsen"),
      e("😆", "lachen", "laut"),
      e("😅", "schwitzen", "lachen", "erleichtert"),
      e("🤣", "kringeln", "lachen", "boden"),
      e("😂", "tränen", "lachen"),
      e("🙂", "lächeln", "leicht"),
      e("🙃", "kopfüber", "ironie"),
      e("😉", "zwinkern", "flirt"),
      e("😊", "erröten", "lächeln", "lieb"),
      e("😇", "engel", "heiligenschein", "unschuldig"),
      e("🥰", "verliebt", "herzen", "lieb"),
      e("😍", "herzaugen", "verliebt", "schwärmen"),
      e("🤩", "sterne", "begeistert", "wow"),
      e("😘", "kuss", "kussmund", "flirt"),
      e("😗", "kuss"),
      e("😚", "kuss", "geschlossen"),
      e("😙", "kuss", "lächeln"),
      e("🥲", "träne", "lächeln", "gerührt"),
      e("😋", "lecker", "zunge", "schmecken"),
      e("😛", "zunge", "frech"),
      e("😜", "zunge", "zwinkern", "frech"),
      e("🤪", "verrückt", "albern"),
      e("😝", "zunge", "augen zu"),
      e("🤗", "umarmen", "umarmung"),
      e("🤭", "hand", "mund", "kichern"),
      e("🤫", "psst", "leise", "geheimnis"),
      e("🤔", "denken", "überlegen", "hmm"),
      e("🫣", "gucken", "schüchtern", "verstecken"),
      e("😐", "neutral", "ausdruckslos"),
      e("😏", "grinsen", "schelmisch", "flirt"),
      e("😒", "genervt", "unbeeindruckt"),
      e("🙄", "augenrollen", "genervt"),
      e("😬", "grimasse", "peinlich"),
      e("😌", "erleichtert", "zufrieden"),
      e("😔", "traurig", "nachdenklich"),
      e("😪", "müde", "schläfrig"),
      e("😴", "schlafen", "müde"),
      e("🥱", "gähnen", "müde"),
      e("😷", "maske", "krank"),
      e("🤒", "fieber", "krank"),
      e("🥵", "heiss", "hitze", "schwitzen"),
      e("🥶", "kalt", "frieren"),
      e("😳", "erröten", "überrascht", "verlegen"),
      e("🥺", "bettelaugen", "bitte", "süss"),
      e("😢", "weinen", "traurig"),
      e("😭", "heulen", "weinen"),
      e("😤", "schnauben", "wütend", "stolz"),
      e("😠", "sauer", "wütend"),
      e("😡", "wütend", "zornig"),
      e("🥳", "party", "feiern", "geburtstag"),
      e("😎", "sonnenbrille", "cool"),
      e("🤓", "nerd", "brille"),
      e("😈", "teufel", "frech", "böse"),
      e("👿", "teufel", "wütend"),
      e("💀", "totenkopf", "tot", "lachen"),
      e("🤡", "clown"),
      e("👻", "geist", "gespenst"),
      e("🙈", "affe", "augen zu", "schäm"),
      e("🙉", "affe", "ohren zu"),
      e("🙊", "affe", "mund zu"),
    ],
  },
  {
    id: "gesten",
    label: "Gesten",
    icon: "👋",
    emojis: [
      e("👋", "winken", "hallo", "tschüss"),
      e("🤚", "hand", "stopp"),
      e("✋", "hand", "high five"),
      e("👌", "okay", "perfekt"),
      e("🤌", "finger", "italienisch"),
      e("🤏", "wenig", "bisschen"),
      e("✌️", "peace", "victory"),
      e("🤞", "daumen drücken", "glück"),
      e("🫰", "herz finger", "geld", "liebe"),
      e("🤟", "love you", "geste"),
      e("🤙", "call me", "anrufen"),
      e("👈", "links", "zeigen"),
      e("👉", "rechts", "zeigen"),
      e("👆", "oben", "zeigen"),
      e("👇", "unten", "zeigen"),
      e("👍", "daumen hoch", "gut", "super"),
      e("👎", "daumen runter", "schlecht"),
      e("👊", "faust", "gruss"),
      e("👏", "klatschen", "applaus", "bravo"),
      e("🙌", "hände hoch", "jubel"),
      e("🫶", "herz hände", "liebe", "danke"),
      e("🙏", "danke", "bitte", "beten"),
      e("💅", "nägel", "maniküre", "style"),
      e("💪", "muskel", "stark"),
      e("👀", "augen", "schauen", "interesse"),
      e("👅", "zunge", "lecken"),
      e("👄", "lippen", "mund", "kuss"),
      e("💋", "kussmund", "lippenstift", "kuss"),
    ],
  },
  {
    id: "liebe",
    label: "Liebe",
    icon: "❤️",
    emojis: [
      e("❤️", "herz", "liebe", "rot"),
      e("🧡", "herz", "orange"),
      e("💛", "herz", "gelb"),
      e("💚", "herz", "grün"),
      e("💙", "herz", "blau"),
      e("💜", "herz", "lila"),
      e("🖤", "herz", "schwarz"),
      e("🤍", "herz", "weiss"),
      e("🩷", "herz", "rosa", "pink"),
      e("💗", "herz", "wachsend"),
      e("💓", "herz", "schlagend"),
      e("💕", "zwei herzen", "verliebt"),
      e("💞", "herzen", "kreisend"),
      e("💘", "herz", "pfeil", "amor"),
      e("💝", "herz", "geschenk"),
      e("💖", "herz", "funkeln"),
      e("💫", "sterne", "schwindelig"),
      e("💯", "hundert", "perfekt", "top"),
      e("🔥", "feuer", "heiss", "hot"),
      e("✨", "funkeln", "glitzer", "sterne"),
      e("💦", "tropfen", "wasser", "schweiss"),
      e("🌹", "rose", "blume", "romantik"),
      e("🌸", "blüte", "blume"),
      e("💐", "blumenstrauss", "blumen"),
      e("🎁", "geschenk", "überraschung"),
      e("🥂", "anstossen", "sekt", "feiern"),
      e("🍾", "champagner", "feiern"),
      e("💎", "diamant", "edelstein", "luxus"),
      e("👑", "krone", "königin", "vip"),
      e("💃", "tanzen", "frau"),
      e("🕺", "tanzen", "mann"),
      e("👠", "highheels", "schuh"),
      e("👙", "bikini", "strand"),
      e("🩱", "badeanzug"),
      e("💍", "ring", "verlobung"),
    ],
  },
  {
    id: "essen",
    label: "Essen",
    icon: "🍕",
    emojis: [
      e("☕", "kaffee", "espresso"),
      e("🍵", "tee"),
      e("🍷", "wein", "rotwein"),
      e("🍸", "cocktail", "martini"),
      e("🍹", "cocktail", "drink", "urlaub"),
      e("🍺", "bier"),
      e("🥃", "whisky", "drink"),
      e("🧉", "mate"),
      e("🍕", "pizza"),
      e("🍔", "burger"),
      e("🍟", "pommes"),
      e("🍣", "sushi"),
      e("🍜", "ramen", "nudeln"),
      e("🥗", "salat", "gesund"),
      e("🍝", "pasta", "nudeln"),
      e("🥩", "steak", "fleisch"),
      e("🍰", "kuchen", "torte"),
      e("🎂", "geburtstag", "torte"),
      e("🍫", "schokolade"),
      e("🍓", "erdbeere"),
      e("🍒", "kirsche"),
      e("🍑", "pfirsich", "po"),
      e("🍆", "aubergine"),
      e("🍦", "eis", "eiscreme"),
      e("🍪", "keks"),
      e("🥐", "croissant", "frühstück"),
    ],
  },
  {
    id: "aktivitaeten",
    label: "Aktivitäten",
    icon: "🎉",
    emojis: [
      e("🎉", "party", "feiern", "konfetti"),
      e("🎊", "konfetti", "party"),
      e("🎶", "musik", "noten"),
      e("🎧", "kopfhörer", "musik"),
      e("🎤", "mikrofon", "singen", "karaoke"),
      e("🎬", "film", "kino", "klappe"),
      e("📸", "foto", "kamera", "bild"),
      e("🎥", "video", "kamera"),
      e("🎮", "gaming", "konsole"),
      e("🎲", "würfel", "spiel"),
      e("♠️", "pik", "karten"),
      e("🎯", "ziel", "treffer"),
      e("💆", "massage", "entspannen"),
      e("🛁", "badewanne", "baden"),
      e("🧖", "sauna", "wellness", "spa"),
      e("🏖️", "strand", "urlaub"),
      e("🌴", "palme", "urlaub"),
      e("🏊", "schwimmen"),
      e("🚴", "fahrrad", "sport"),
      e("🏋️", "fitness", "training", "gym"),
      e("🧘", "yoga", "meditation"),
      e("🕯️", "kerze", "romantik"),
      e("🛏️", "bett", "schlafen"),
      e("🌙", "mond", "nacht"),
      e("⭐", "stern"),
      e("☀️", "sonne"),
    ],
  },
  {
    id: "reisen",
    label: "Reisen",
    icon: "✈️",
    emojis: [
      e("✈️", "flugzeug", "reise", "fliegen"),
      e("🚗", "auto", "fahren"),
      e("🚕", "taxi"),
      e("🚙", "suv", "auto"),
      e("🏎️", "rennwagen", "schnell"),
      e("🚄", "zug", "bahn"),
      e("🚁", "hubschrauber"),
      e("🛥️", "boot", "yacht"),
      e("🏨", "hotel"),
      e("🏠", "zuhause", "haus"),
      e("🏙️", "stadt", "skyline"),
      e("🌍", "welt", "erde", "europa"),
      e("🗺️", "karte", "reise"),
      e("🧳", "koffer", "gepäck"),
      e("📍", "ort", "standort", "pin"),
      e("🕐", "uhr", "zeit"),
      e("📅", "kalender", "termin"),
      e("⏰", "wecker", "zeit"),
    ],
  },
  {
    id: "objekte",
    label: "Objekte",
    icon: "📱",
    emojis: [
      e("📱", "handy", "smartphone"),
      e("📞", "telefon", "anrufen"),
      e("☎️", "telefon"),
      e("💬", "nachricht", "chat", "sprechblase"),
      e("💌", "liebesbrief", "brief"),
      e("📧", "mail", "email"),
      e("🔒", "schloss", "sicher", "diskret"),
      e("🔑", "schlüssel"),
      e("💳", "karte", "bezahlen"),
      e("💶", "euro", "geld"),
      e("💰", "geld", "sack"),
      e("🎀", "schleife", "geschenk"),
      e("🧴", "öl", "lotion", "massage"),
      e("🚿", "dusche"),
      e("🪞", "spiegel"),
      e("💄", "lippenstift", "makeup"),
      e("👗", "kleid"),
      e("🕶️", "sonnenbrille"),
      e("⌚", "uhr", "armbanduhr"),
      e("🔞", "18", "erwachsene", "fsk"),
    ],
  },
  {
    id: "symbole",
    label: "Symbole",
    icon: "✅",
    emojis: [
      e("✅", "haken", "erledigt", "ja"),
      e("❌", "kreuz", "nein", "falsch"),
      e("❗", "ausrufezeichen", "wichtig"),
      e("❓", "frage", "fragezeichen"),
      e("⚠️", "warnung", "achtung"),
      e("🆗", "ok"),
      e("🔝", "top", "oben"),
      e("🆕", "neu"),
      e("🔥", "feuer", "hot"),
      e("💤", "schlafen", "zzz"),
      e("🚫", "verboten", "nein"),
      e("♾️", "unendlich"),
      e("🎵", "note", "musik"),
      e("💭", "gedanke", "denken"),
      e("🗯️", "wut", "sprechblase"),
      e("🔴", "rot", "punkt"),
      e("🟢", "grün", "online"),
      e("⚫", "schwarz", "punkt"),
    ],
  },
];

/** Sucht über Zeichen und Stichwörter aller Kategorien. */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const treffer: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emojis) {
      if (entry.char === q || entry.keywords.some((k) => k.includes(q))) treffer.push(entry);
    }
  }
  return treffer;
}
